package com.xiong.entity;

public class BuyCar {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_car.username
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_car.milk_tea_name
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private String milkTeaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_car.milk_tea_count
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private Integer milkTeaCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_car.username
     *
     * @return the value of buy_car.username
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_car.username
     *
     * @param username the value for buy_car.username
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_car.milk_tea_name
     *
     * @return the value of buy_car.milk_tea_name
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public String getMilkTeaName() {
        return milkTeaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_car.milk_tea_name
     *
     * @param milkTeaName the value for buy_car.milk_tea_name
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setMilkTeaName(String milkTeaName) {
        this.milkTeaName = milkTeaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_car.milk_tea_count
     *
     * @return the value of buy_car.milk_tea_count
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public Integer getMilkTeaCount() {
        return milkTeaCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_car.milk_tea_count
     *
     * @param milkTeaCount the value for buy_car.milk_tea_count
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setMilkTeaCount(Integer milkTeaCount) {
        this.milkTeaCount = milkTeaCount;
    }

	@Override
	public String toString() {
		return "BuyCar [username=" + username + ", milkTeaName=" + milkTeaName + ", milkTeaCount=" + milkTeaCount + "]";
	}
    
    
}