package com.xiong.entity;

public class Discounts {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discounts.id
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discounts.discounts_id
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private String discountsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discounts.discounts_count
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private Integer discountsCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discounts.discounts_price
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private Integer discountsPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discounts.how_can_use
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private Integer howCanUse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discounts.use_begin_time
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private String useBeginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discounts.use_finish_time
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private String useFinishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discounts.contact_way
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private String contactWay;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discounts.id
     *
     * @return the value of discounts.id
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discounts.id
     *
     * @param id the value for discounts.id
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discounts.discounts_id
     *
     * @return the value of discounts.discounts_id
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public String getDiscountsId() {
        return discountsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discounts.discounts_id
     *
     * @param discountsId the value for discounts.discounts_id
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setDiscountsId(String discountsId) {
        this.discountsId = discountsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discounts.discounts_count
     *
     * @return the value of discounts.discounts_count
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public Integer getDiscountsCount() {
        return discountsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discounts.discounts_count
     *
     * @param discountsCount the value for discounts.discounts_count
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setDiscountsCount(Integer discountsCount) {
        this.discountsCount = discountsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discounts.discounts_price
     *
     * @return the value of discounts.discounts_price
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public Integer getDiscountsPrice() {
        return discountsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discounts.discounts_price
     *
     * @param discountsPrice the value for discounts.discounts_price
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setDiscountsPrice(Integer discountsPrice) {
        this.discountsPrice = discountsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discounts.how_can_use
     *
     * @return the value of discounts.how_can_use
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public Integer getHowCanUse() {
        return howCanUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discounts.how_can_use
     *
     * @param howCanUse the value for discounts.how_can_use
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setHowCanUse(Integer howCanUse) {
        this.howCanUse = howCanUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discounts.use_begin_time
     *
     * @return the value of discounts.use_begin_time
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public String getUseBeginTime() {
        return useBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discounts.use_begin_time
     *
     * @param useBeginTime the value for discounts.use_begin_time
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setUseBeginTime(String useBeginTime) {
        this.useBeginTime = useBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discounts.use_finish_time
     *
     * @return the value of discounts.use_finish_time
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public String getUseFinishTime() {
        return useFinishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discounts.use_finish_time
     *
     * @param useFinishTime the value for discounts.use_finish_time
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setUseFinishTime(String useFinishTime) {
        this.useFinishTime = useFinishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discounts.contact_way
     *
     * @return the value of discounts.contact_way
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public String getContactWay() {
        return contactWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discounts.contact_way
     *
     * @param contactWay the value for discounts.contact_way
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setContactWay(String contactWay) {
        this.contactWay = contactWay;
    }

	@Override
	public String toString() {
		return "Discounts [id=" + id + ", discountsId=" + discountsId + ", discountsCount=" + discountsCount
				+ ", discountsPrice=" + discountsPrice + ", howCanUse=" + howCanUse + ", useBeginTime=" + useBeginTime
				+ ", useFinishTime=" + useFinishTime + ", contactWay=" + contactWay + "]";
	}
    
    
}