package com.xiong.entity;

public class Evaluate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluate.milk_tea_name
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private String milkTeaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluate.username
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluate.evaluate_content
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private String evaluateContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate.milk_tea_name
     *
     * @return the value of evaluate.milk_tea_name
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public String getMilkTeaName() {
        return milkTeaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate.milk_tea_name
     *
     * @param milkTeaName the value for evaluate.milk_tea_name
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setMilkTeaName(String milkTeaName) {
        this.milkTeaName = milkTeaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate.username
     *
     * @return the value of evaluate.username
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate.username
     *
     * @param username the value for evaluate.username
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate.evaluate_content
     *
     * @return the value of evaluate.evaluate_content
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public String getEvaluateContent() {
        return evaluateContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate.evaluate_content
     *
     * @param evaluateContent the value for evaluate.evaluate_content
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setEvaluateContent(String evaluateContent) {
        this.evaluateContent = evaluateContent;
    }
}