package com.xiong.entity;

public class MilkTeaInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column milk_tea_info.id
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column milk_tea_info.milk_tea_name
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private String milkTeaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column milk_tea_info.milk_tea_img_src
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private String milkTeaImgSrc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column milk_tea_info.milk_tea_normalprice
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private String milkTeaNormalprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column milk_tea_info.milk_tea_specialprice
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private String milkTeaSpecialprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column milk_tea_info.milk_tea_put_data
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private String milkTeaPutData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column milk_tea_info.milk_tea_good_count
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private Integer milkTeaGoodCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column milk_tea_info.milk_tea_inventory
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private Integer milkTeaInventory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column milk_tea_info.milk_tea_sales
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private Integer milkTeaSales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column milk_tea_info.milk_tea_freight
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private Integer milkTeaFreight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column milk_tea_info.milk_tea_describe
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private String milkTeaDescribe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column milk_tea_info.id
     *
     * @return the value of milk_tea_info.id
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column milk_tea_info.id
     *
     * @param id the value for milk_tea_info.id
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column milk_tea_info.milk_tea_name
     *
     * @return the value of milk_tea_info.milk_tea_name
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public String getMilkTeaName() {
        return milkTeaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column milk_tea_info.milk_tea_name
     *
     * @param milkTeaName the value for milk_tea_info.milk_tea_name
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setMilkTeaName(String milkTeaName) {
        this.milkTeaName = milkTeaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column milk_tea_info.milk_tea_img_src
     *
     * @return the value of milk_tea_info.milk_tea_img_src
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public String getMilkTeaImgSrc() {
        return milkTeaImgSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column milk_tea_info.milk_tea_img_src
     *
     * @param milkTeaImgSrc the value for milk_tea_info.milk_tea_img_src
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setMilkTeaImgSrc(String milkTeaImgSrc) {
        this.milkTeaImgSrc = milkTeaImgSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column milk_tea_info.milk_tea_normalprice
     *
     * @return the value of milk_tea_info.milk_tea_normalprice
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public String getMilkTeaNormalprice() {
        return milkTeaNormalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column milk_tea_info.milk_tea_normalprice
     *
     * @param milkTeaNormalprice the value for milk_tea_info.milk_tea_normalprice
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setMilkTeaNormalprice(String milkTeaNormalprice) {
        this.milkTeaNormalprice = milkTeaNormalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column milk_tea_info.milk_tea_specialprice
     *
     * @return the value of milk_tea_info.milk_tea_specialprice
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public String getMilkTeaSpecialprice() {
        return milkTeaSpecialprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column milk_tea_info.milk_tea_specialprice
     *
     * @param milkTeaSpecialprice the value for milk_tea_info.milk_tea_specialprice
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setMilkTeaSpecialprice(String milkTeaSpecialprice) {
        this.milkTeaSpecialprice = milkTeaSpecialprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column milk_tea_info.milk_tea_put_data
     *
     * @return the value of milk_tea_info.milk_tea_put_data
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public String getMilkTeaPutData() {
        return milkTeaPutData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column milk_tea_info.milk_tea_put_data
     *
     * @param milkTeaPutData the value for milk_tea_info.milk_tea_put_data
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setMilkTeaPutData(String milkTeaPutData) {
        this.milkTeaPutData = milkTeaPutData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column milk_tea_info.milk_tea_good_count
     *
     * @return the value of milk_tea_info.milk_tea_good_count
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public Integer getMilkTeaGoodCount() {
        return milkTeaGoodCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column milk_tea_info.milk_tea_good_count
     *
     * @param milkTeaGoodCount the value for milk_tea_info.milk_tea_good_count
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setMilkTeaGoodCount(Integer milkTeaGoodCount) {
        this.milkTeaGoodCount = milkTeaGoodCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column milk_tea_info.milk_tea_inventory
     *
     * @return the value of milk_tea_info.milk_tea_inventory
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public Integer getMilkTeaInventory() {
        return milkTeaInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column milk_tea_info.milk_tea_inventory
     *
     * @param milkTeaInventory the value for milk_tea_info.milk_tea_inventory
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setMilkTeaInventory(Integer milkTeaInventory) {
        this.milkTeaInventory = milkTeaInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column milk_tea_info.milk_tea_sales
     *
     * @return the value of milk_tea_info.milk_tea_sales
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public Integer getMilkTeaSales() {
        return milkTeaSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column milk_tea_info.milk_tea_sales
     *
     * @param milkTeaSales the value for milk_tea_info.milk_tea_sales
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setMilkTeaSales(Integer milkTeaSales) {
        this.milkTeaSales = milkTeaSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column milk_tea_info.milk_tea_freight
     *
     * @return the value of milk_tea_info.milk_tea_freight
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public Integer getMilkTeaFreight() {
        return milkTeaFreight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column milk_tea_info.milk_tea_freight
     *
     * @param milkTeaFreight the value for milk_tea_info.milk_tea_freight
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setMilkTeaFreight(Integer milkTeaFreight) {
        this.milkTeaFreight = milkTeaFreight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column milk_tea_info.milk_tea_describe
     *
     * @return the value of milk_tea_info.milk_tea_describe
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public String getMilkTeaDescribe() {
        return milkTeaDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column milk_tea_info.milk_tea_describe
     *
     * @param milkTeaDescribe the value for milk_tea_info.milk_tea_describe
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setMilkTeaDescribe(String milkTeaDescribe) {
        this.milkTeaDescribe = milkTeaDescribe;
    }

	@Override
	public String toString() {
		return "MilkTeaInfo [id=" + id + ", milkTeaName=" + milkTeaName + ", milkTeaImgSrc=" + milkTeaImgSrc
				+ ", milkTeaNormalprice=" + milkTeaNormalprice + ", milkTeaSpecialprice=" + milkTeaSpecialprice
				+ ", milkTeaPutData=" + milkTeaPutData + ", milkTeaGoodCount=" + milkTeaGoodCount
				+ ", milkTeaInventory=" + milkTeaInventory + ", milkTeaSales=" + milkTeaSales + ", milkTeaFreight="
				+ milkTeaFreight + ", milkTeaDescribe=" + milkTeaDescribe + "]";
	}
    
    
}