package com.xiong.entity;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.id
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.order_id
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.username
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.remarks
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.discounts_num
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private String discountsNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.integral_num
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private String integralNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.order_begin_time
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private String orderBeginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.order_finish_time
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private String orderFinishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.distribution_man
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private String distributionMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.adress
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private String adress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.order_state
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private String orderState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.order_finish_state
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private String orderFinishState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.id
     *
     * @return the value of order_.id
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.id
     *
     * @param id the value for order_.id
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.order_id
     *
     * @return the value of order_.order_id
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.order_id
     *
     * @param orderId the value for order_.order_id
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.username
     *
     * @return the value of order_.username
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.username
     *
     * @param username the value for order_.username
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.remarks
     *
     * @return the value of order_.remarks
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.remarks
     *
     * @param remarks the value for order_.remarks
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.discounts_num
     *
     * @return the value of order_.discounts_num
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public String getDiscountsNum() {
        return discountsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.discounts_num
     *
     * @param discountsNum the value for order_.discounts_num
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setDiscountsNum(String discountsNum) {
        this.discountsNum = discountsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.integral_num
     *
     * @return the value of order_.integral_num
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public String getIntegralNum() {
        return integralNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.integral_num
     *
     * @param integralNum the value for order_.integral_num
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setIntegralNum(String integralNum) {
        this.integralNum = integralNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.order_begin_time
     *
     * @return the value of order_.order_begin_time
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public String getOrderBeginTime() {
        return orderBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.order_begin_time
     *
     * @param orderBeginTime the value for order_.order_begin_time
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setOrderBeginTime(String orderBeginTime) {
        this.orderBeginTime = orderBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.order_finish_time
     *
     * @return the value of order_.order_finish_time
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public String getOrderFinishTime() {
        return orderFinishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.order_finish_time
     *
     * @param orderFinishTime the value for order_.order_finish_time
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setOrderFinishTime(String orderFinishTime) {
        this.orderFinishTime = orderFinishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.distribution_man
     *
     * @return the value of order_.distribution_man
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public String getDistributionMan() {
        return distributionMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.distribution_man
     *
     * @param distributionMan the value for order_.distribution_man
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setDistributionMan(String distributionMan) {
        this.distributionMan = distributionMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.adress
     *
     * @return the value of order_.adress
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public String getAdress() {
        return adress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.adress
     *
     * @param adress the value for order_.adress
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setAdress(String adress) {
        this.adress = adress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.order_state
     *
     * @return the value of order_.order_state
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public String getOrderState() {
        return orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.order_state
     *
     * @param orderState the value for order_.order_state
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setOrderState(String orderState) {
        this.orderState = orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.order_finish_state
     *
     * @return the value of order_.order_finish_state
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public String getOrderFinishState() {
        return orderFinishState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.order_finish_state
     *
     * @param orderFinishState the value for order_.order_finish_state
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setOrderFinishState(String orderFinishState) {
        this.orderFinishState = orderFinishState;
    }
}