package com.xiong.entity;

public class OrderCommodity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity.order_id
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity.milk_tea_name
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private String milkTeaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_commodity.milk_tea_count
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private Integer milkTeaCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity.order_id
     *
     * @return the value of order_commodity.order_id
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity.order_id
     *
     * @param orderId the value for order_commodity.order_id
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity.milk_tea_name
     *
     * @return the value of order_commodity.milk_tea_name
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public String getMilkTeaName() {
        return milkTeaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity.milk_tea_name
     *
     * @param milkTeaName the value for order_commodity.milk_tea_name
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setMilkTeaName(String milkTeaName) {
        this.milkTeaName = milkTeaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_commodity.milk_tea_count
     *
     * @return the value of order_commodity.milk_tea_count
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public Integer getMilkTeaCount() {
        return milkTeaCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_commodity.milk_tea_count
     *
     * @param milkTeaCount the value for order_commodity.milk_tea_count
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setMilkTeaCount(Integer milkTeaCount) {
        this.milkTeaCount = milkTeaCount;
    }
}