package com.xiong.entity;

import java.io.Serializable;

public class User implements Serializable{
	private static final long serialVersionUID = -8611278681130083647L;

	private Integer id;

    private String headImgSrc;

    private String username;

    private String pass;

    private Integer balance;

    private Integer integral;

    private Integer age;

    private String birthday;

    private String sex;

    private String contactWay;

    private String signature;

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.head_img_src
     *
     * @return the value of user.head_img_src
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public String getHeadImgSrc() {
        return headImgSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.head_img_src
     *
     * @param headImgSrc the value for user.head_img_src
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setHeadImgSrc(String headImgSrc) {
        this.headImgSrc = headImgSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.pass
     *
     * @return the value of user.pass
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public String getPass() {
        return pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.pass
     *
     * @param pass the value for user.pass
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setPass(String pass) {
        this.pass = pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.balance
     *
     * @return the value of user.balance
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public Integer getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.balance
     *
     * @param balance the value for user.balance
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setBalance(Integer balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.integral
     *
     * @return the value of user.integral
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public Integer getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.integral
     *
     * @param integral the value for user.integral
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setIntegral(Integer integral) {
        this.integral = integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.age
     *
     * @return the value of user.age
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.age
     *
     * @param age the value for user.age
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.birthday
     *
     * @return the value of user.birthday
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.birthday
     *
     * @param birthday the value for user.birthday
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sex
     *
     * @return the value of user.sex
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sex
     *
     * @param sex the value for user.sex
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.contact_way
     *
     * @return the value of user.contact_way
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public String getContactWay() {
        return contactWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.contact_way
     *
     * @param contactWay the value for user.contact_way
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setContactWay(String contactWay) {
        this.contactWay = contactWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.signature
     *
     * @return the value of user.signature
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.signature
     *
     * @param signature the value for user.signature
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setSignature(String signature) {
        this.signature = signature;
    }

	@Override
	public String toString() {
		return "User [id=" + id + ", headImgSrc=" + headImgSrc + ", username=" + username + ", pass=" + pass
				+ ", balance=" + balance + ", integral=" + integral + ", age=" + age + ", birthday=" + birthday
				+ ", sex=" + sex + ", contactWay=" + contactWay + ", signature=" + signature + "]";
	}
    
    
}