package com.xiong.entity;

public class WhoHaveDiscounts {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column who_have_discounts.username
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column who_have_discounts.discounts_id
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private String discountsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column who_have_discounts.have_discounts_count
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private Integer haveDiscountsCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column who_have_discounts.discounts_state
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    private String discountsState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column who_have_discounts.username
     *
     * @return the value of who_have_discounts.username
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column who_have_discounts.username
     *
     * @param username the value for who_have_discounts.username
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column who_have_discounts.discounts_id
     *
     * @return the value of who_have_discounts.discounts_id
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public String getDiscountsId() {
        return discountsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column who_have_discounts.discounts_id
     *
     * @param discountsId the value for who_have_discounts.discounts_id
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setDiscountsId(String discountsId) {
        this.discountsId = discountsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column who_have_discounts.have_discounts_count
     *
     * @return the value of who_have_discounts.have_discounts_count
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public Integer getHaveDiscountsCount() {
        return haveDiscountsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column who_have_discounts.have_discounts_count
     *
     * @param haveDiscountsCount the value for who_have_discounts.have_discounts_count
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setHaveDiscountsCount(Integer haveDiscountsCount) {
        this.haveDiscountsCount = haveDiscountsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column who_have_discounts.discounts_state
     *
     * @return the value of who_have_discounts.discounts_state
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public String getDiscountsState() {
        return discountsState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column who_have_discounts.discounts_state
     *
     * @param discountsState the value for who_have_discounts.discounts_state
     *
     * @mbg.generated Wed Apr 10 16:31:11 CST 2019
     */
    public void setDiscountsState(String discountsState) {
        this.discountsState = discountsState;
    }

	@Override
	public String toString() {
		return "WhoHaveDiscounts [username=" + username + ", discountsId=" + discountsId + ", haveDiscountsCount="
				+ haveDiscountsCount + ", discountsState=" + discountsState + "]";
	}
    
    
}